import dimensional_compactification_quantum_field_theory_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace dimensional_compactification_quantum_field_theory_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end dimensional_compactification_quantum_field_theory_theorem_canonical_lane_mathlib
end HautevilleHouse
